# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Pineapple
tagline:             'a Project blog'
description:         'Starting a blog to post interesting projects.'
url:                 http://edmondchensj.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Edmond Chen
  url:               -
  email:             edmondchensj@gmail.com

# Custom vars
version:             1.0.0
